- name: Configure Ansible

  hosts: localhost

  become: false

  gather_facts: false



  tasks:

    - name: Set working directory

      ansible.builtin.set_fact:

        ansible_work_dir: /home/user/automation



    - name: Disable host key checking

      ansible.builtin.lineinfile:

        path: "{{ ansible_work_dir }}/ansible.cfg"

        regexp: '^#?(host_key_checking\s*)='

        line: 'host_key_checking = False'

        backup: yes



    - name: Set server IPs

      ansible.builtin.set_fact:

        srv1_ip: "{{ lookup('env', 'srv1_ip') }}"

        srv2_ip: "{{ lookup('env', 'srv2_ip') }}"

        srv3_ip: "{{ lookup('env', 'srv3_ip') }}"

    

- name: Gather server information

  hosts: all

  become: true

  gather_facts: true



  tasks:

    - name: Get kernel version

      ansible.builtin.shell: uname -r

      register: kernel_version



    - name: Get boot image

      ansible.builtin.shell: cat /proc/cmdline | awk -F ' ' '{print $1}'

      register: boot_image



    - name: Get Python version

      ansible.builtin.shell: python --version | awk '{print $2}'

      register: python_version



    - name: Generate report

      ansible.builtin.copy:

        content: |

          kernel_version: {{ kernel_version.stdout }}

          boot_image: {{ boot_image.stdout }}

          python_version: {{ python_version.stdout }}

        dest: "{{ ansible_work_dir }}/{{ inventory_hostname }}.yml"


