version: '3'

services:

  postgres:

    image: postgres

    restart: always

    environment:

      POSTGRES_PASSWORD: superpuper

      POSTGRES_USER: postgres

      POSTGRES_DB: example

    ports:

      - "5432:5432"

    volumes:

      - postgres-data:/var/lib/postgresql/data



  phpmyadmin:

    image: phpmyadmin

    restart: always

    environment:

      PMA_HOST: postgres

      PMA_USER: postgres

      PMA_PASSWORD: superpuper

    ports:

      - "8080:80"

    depends_on:

      - postgres



volumes:

  postgres-data:
